#config.yaml

hyperparameters:
  dataset_path: "~/datasets"
  cuda: True
  DEVICE: torch.device("cuda" if cuda else "cpu")
  batch_size: 256
  x_dim: 784
  hidden_dim: 400
  latent_dim: 20
  learning_rate: 1e-3
  epochs: 20